# Generated by Django 3.1.3 on 2023-05-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
            preserve_default=False,
        ),
    ]
